require('options')
require('keymaps')

require('plugins.lazy')
require('plugins.oil')
require('plugins.telescope')
require('plugins.treesitter')
require('plugins.lsp')
require('plugins.autocompletion')
require('plugins.harpoon')
require('plugins.notify')
require('plugins.gitsigns')
require('plugins.neogit')
require('plugins.obsidian')
require('plugins.copilot')

require('theme')
